/*
SQLyog Community v13.1.9 (64 bit)
MySQL - 10.4.24-MariaDB : Database - projekt
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`projekt` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

USE `projekt`;

/*Table structure for table `articles` */

DROP TABLE IF EXISTS `articles`;

CREATE TABLE `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `picture` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `archive` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `articles` */

insert  into `articles`(`id`,`title`,`description`,`category`,`picture`,`content`,`archive`) values 
(28,'Lappland','Guard, Lord','ranged','lappland.png','Supposedly Rhodes Island has very strict psychological tests, but Lappland\'s examiner has clearly never heard her maniacal laugh. Or maybe they made an exception for her unique ability to deal Arts Damage and Silence enemies.\r\n\r\nWhatever the case may be, Lappland now serves under Rhodes Island as a Ranged Guard. Her range allows her to hit flying enemies or be positioned behind a blocker, though her ranged attacks will deal 80% damage. Sundial, her first skill, is ideal for a frontline position, as it permanently increases her damage and grants a chance to resist incoming Physical attacks. Her second skill,  Wolf Spirit, increases her DPS potential by switching her damage to Arts, allowing her to hit an extra target, and removing the ranged attack penalty. This makes it a great option when placing her in the backline. \r\n\r\nWhile these skills are useful in their own right, Lappland\'s most impressive technique is disabling the enemy\'s special abilities with her Mental Destruction talent. This is invaluable for challenging content and shutting down enemies with devastating specials.  While Lappland\'s damage output may not be as high or consistent as other Guards, she remains irreplacable because of  with her unique Talent.  Lappland is a highly sought after Operator that you will be thankful to have as part of your squad (as long as you don\'t get in between her and Texas)',0),
(29,'Ifrit','Burninator / Blast caster','ranged','ifrit.jpg','Though Ifrit’s apologies for burning down parts of Rhodes Island are very heartfelt, the best way for her to make up for her actions is by burning down your enemies on the battlefield instead. And oh boy, is she capable of doing that! Ifrit is a 6* AoE Caster who is notable for her DPS, her flat stat Debuffs, and her unusual attack range, where she damages all enemies in a long line straight from her position.\r\n\r\nEverything about Ifrit is meant to send your enemies straight to the crematorium. Her first Talent, Spiritual Dissolution, decreases the RES of enemies within her attack range, while her E2 Talent, Rhine Loop, increases her rate of SP gain. Together, these Talents give Ifrit some monstrous DPS potential that is multiplied by her Skills. Pyroclasm (Skill 2) increases the damage of her next attack and causes it to inflict a flat DEF debuff and a burn effect that deals damage over time. This Skill greatly enhances the damage of physical Operators on her team and is generally the preferred Skill. On the other hand, Scorched Earth (Skill 3) temporarily transforms Ifrit’s regular attack into more of an “aura” that deals Arts damage to enemies every second and further decreases their RES, making it better for burning down bosses and benefiting allied Casters. However, this Skill causes Ifrit to lose HP while it is active and cannot hit aerial enemies, so it must be used wisely.\r\n\r\nIn fact, “must be used wisely” is a good rule of thumb for Ifrit in general. Her straight-line attack range is not easy to utilize on all maps and her Skills work best when the rest of her team is tailored around them. She also suffers from the usual disadvantages of AoE Casters: her attack speed is slow, she is very fragile, and deploying her is very expensive. The payoff is worth it, however; her DPS is insane and flat stat debuffs are quite uncommon in Arknights. Provide the fuel for Ifrit’s flamethrower and she will put it to very, very good use.',0),
(30,'Kal\'tsit','ST / Medic','ranged','kaltsit.jpg','As a Medic, Kal’tsit’s regular attack does restore HP to allies. However, she has very low ATK for a ST Medic (more on par with a Wide-Range Medic, for context), an increased attack range (the same attack range as an AoE Sniper, weirdly), and unusual targeting: she will always prioritize healing herself and Mon3tr over other targets. Mon3tr is a summonable minion who can be placed anywhere on the field, but his DEF is reduced to 0 if he’s not deployed within Kal’tsit’s attack range. Fortunately, Mon3tr has a pretty quick redeployment time, so it’s not the end of the world if he dies. In fact, Kal’tsit’s E2 Talent—Non-Damaging Restructuring—inflicts Pure damage and Stun on nearby enemies when Mon3tr’s HP hits 0.\r\n\r\nKal’tsit’s Skills also involve Mon3tr in interesting ways. Her S1, Command: Structural Fortification, is the only Skill she can use while Mon3tr is not on the field. Command: Structural Fortification buffs DEF for Kal’tsit and Mon3tr as well as giving Kal’tsit 50% Physical Dodge. S2 is a more offensive choice: Command: Tactical Coordination increases Kal’tsit’s attack speed (thus her rate of healing) and Mon3tr’s ATK, while also giving Mon3tr the ability to attack a number of enemies equal to his Block count, like an AoE Guard. Even more powerful is Command: Meltdown, Kal’tsit’s S3, which increases Mon3tr’s ATK and DEF and causes him to deal Pure damage. However, S2 and S3 cannot be used period unless Mon3tr is deployed on the field. Kal’tsit can’t even gain SP for these Skills unless Mon3tr is alive!',0),
(31,'Kroos','Anti-Air / Marksman','ranged','Kroos.jpg','Some Doctors disparage Kroos for her drawling voice and her repetitive “Ko~ko~da~yo” catchphrase (which roughly translates to “I’m here” or “Here I am”). However, many other Doctors swear by Kroos as a staple Sniper for the early- and mid-game of Arknights. A 3★ Anti-Air Sniper with surprising burst damage potential, Kroos can even pull her weight in difficult late-game stages, especially if you don’t have multiple higher-rarity Snipers who can replace her.\r\n\r\nThe trick is in how smoothly Kroos’s kit synergizes with itself. Her Talent, Targeting – Primary, has a random chance to increase the damage of her attacks (like a critical hit in other games). Meanwhile, her Double Tap – Auto Skill automatically triggers every few attacks and causes her to shoot two stronger arrows at once. With her naturally quick rate of fire and the constant extra shots from her Skill, Kroos activates her Talent quite frequently, punching through enemies at a terrifying rate. As a 3★ unit, her cheap DP cost and low investment cost are appealing bonuses, as well as being able to max Potential easily.\r\n\r\nOf course, being a 3★ unit also means that Kroos cannot E2-promote, which puts a cap on how much she can grow to help the team. Promotion gives higher-rarity Operators access to more levels and additional Skills, giving them an advantage. On the other hand, many stages are easier if you deploy multiple Snipers, and while Kroos may fall behind over time, she’ll remain an excellent backup Sniper for much longer than you might expect. So look out, drones! “Ko~ko~da~yo!”',0),
(32,'Broca','AOE / Centurion','melee','broca.jpg','Does Broca’s scary expression unsettle you? As a bodyguard for a gang leader, Broca trained himself to maintain a sinister expression at all times in order to look intimidating. Of course, who needs a scary expression when you’ve got a giant electrified drill? As a 5* AoE Guard, Broca strikes fear (and metal) into the hearts of multiple enemies at once, attacking as many enemies as he can Block and dealing both physical and Arts damage to his victims.\r\n\r\nBroca is built for mass murder. Not only can he Block-3 once he E2-promotes, but his Drill Fortification Talent increases his ATK and DEF whenever he is blocking 2 or more foes at the same time. His Skills ensure that he has enough DPS for every combatant to get a piece, especially his Skill 2, High Voltage Current. In addition to a huge ATK boost and a Slow effect, it also turns Broca’s attacks into Arts damage and extends his attack range, allowing him to attack from safely behind another Operator if he so desires. Even with the downsides (the Skill reduces Broca’s attack speed and self-Stuns once it ends), the DPS from this Skill is simply insane.\r\n\r\nIn order to attain this kind of damage potential, Broca has had to min-max for DPS over survivability. Most AoE Guards have some kind of defensive tool to help them survive Blocking multiple enemies at once, but Broca only gets a small DEF boost from his Talent, which usually won’t save him if things go south. Using High Voltage Current also requires an excellent sense of timing or an extra Operator to block for Broca, as anything he doesn’t kill can walk right past him once he is Stunned. However, “things Broca doesn’t kill” is a pretty small pool of names. Very few enemies can survive Broca’s full voltaic fury, making him well worth the effort to deploy and use.',0),
(34,'Blemishine','Healing / Guardian','melee','blemi.jpg','Blemishine is Nearl’s sister and Whislash’s niece. When Nearl contracted Oripathy and was forced to leave Kazimierz, Blemishine had to step up and take her sister’s place as the lead knight of the family. This position has dragged Blemishine through a crushing grind of backstabbing gloryseekers, obsessive fans, and the massive corporate system the Kazimierz knighthood has become. Perhaps it’s no surprise that she has left it all behind and come to Rhodes Island, joining her disgraced sister as a very versatile 6* Healing Defender: she smites her enemies with physical and Arts DPS, provides HP and SP restoration for her allies, and gently lulls her opponents to Sleep.\r\n\r\nThe Sleep status stops its targets from moving or acting, but it also makes them invincible to incoming damage. Well, not anymore! Blemishine’s Mercy Talent allows her to attack Sleeping targets—in fact, she prioritizes them and has bonus ATK when striking them. This broadens the range of targets that Blemishine can hit, which is important because Blemishine is very attack-dependent for her Skills.',0),
(35,'Surtr','Arts Fighter','melee','surrt.jpg','Surtr is an Infected who has dozens of memories that contradict each other, practically no talent for Originium Arts, and a giant flaming broadsword that can casually destroy anything that gets in her way. To say she is an enigma would be an understatement: nothing is known about her (or the giant flaming broadsword) and there doesn’t seem to be much chance of finding answers anytime soon. This doesn’t bother Surtr, though. She’s happy to kill some time at Rhodes Island as a 6* Arts Guard, bringing her unstoppable DPS and undefeatable survivability to the table. And then slicing the table in half.\r\n\r\nFor a person who can barely use Originium Arts, Surtr is a stupidly powerful Arts DPS unit. Her first Talent, Molten Flame, causes her to ignore a flat amount of enemy RES, making it that much more difficult for enemies to withstand her onslaught. Her E2 Talent, Remnant Ash, gives Surtr several seconds of immortality when she takes lethal damage and then retreats her from the field; even death will not stop Surtr from killing a few more foes!\r\n\r\nAnd there’s no doubt that killing her foes is exactly what Surtr will be doing. Her first Skill, Laevatain, is a quick-charging auto Skill that dramatically increases her ATK for her next attack. If she kills her target with this Skill, it immediately recharges. If facing a steady stream of enemies she can one-shot, Surtr can keep using this Skill forever—and that’s just her first Skill! Her second, Molten Giant, widens the scope of her attack: her ATK increases, her attack range increases, and the number of targets she can hit increases. Furthermore, if Surtr is only hitting one target, the ATK buff increases in strength, making this a great general-purpose Skill.',0),
(36,'La Pluma','Reaper Guard','melee','lapuss.jpg','The “Reaper Guard” archetype is something of a cross between an AoE Guard and an Enmity Guard. La Pluma cannot be directly healed by allies, like an Enmity Guard, and she can attack multiple enemies in an AoE. She has an interesting attack range that strikes three grids horizontally in front of her, and she hits all enemies within that range with every attack. Her Trait causes her to recover HP for each enemy that she hits, up to a maximum of her Block count (she has Block-1 at E0 and Block-2 at E1/E2). So, if La Pluma is E0 and she hits three enemies with one swing, she’ll heal herself once (because Block-1). But if she’s E1 and she hits three enemies, she’ll heal herself twice (because at E1 she has Block-2).\r\n\r\nLa Pluma’s Trait is actually the hardest part of her kit to explain. The rest is quite simple. Her Talent, Into the Groove, increases her ASPD (up to a cap) for each enemy she kills on a given map. With her true AoE attacks and good damage output, this won’t be too difficult to get stacked up most of the time. Her S1, Rapid Slashing, is an automatic Skill that causes her next attack to hit twice for increased damage. And her S2, Reap, reduces her attack interval (and her attacks are already quite quick!) while increasing her ATK. The ATK buff from Reap is increased further if La Pluma is attacking enemies with less than half their HP. Both Skills result not only in increased damage but also increased healing, as dealing multiple hits and attacking faster will trigger La Pluma’s self-healing Trait more often. Her self-sustain and high damage potential make her an excellent cornerstone unit for soloing lanes and holding off enemies without much support (S2 especially makes her a nigh-unkillable damage machine for its duration).',0);

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=108 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`username`,`password`,`level`) values 
(101,'Termostat','$2y$10$wcCfWetfws1BHHS4vcuvieWsYY.yEB0./8xJD.1Hbh5klFxMR1HzW',1),
(102,'User','$2y$10$2VDDh9Ti05.Af5QCK.4cI.kW8Y8x6k55PI.FAiB5.lezNEc6T3aSa',0),
(103,'userbuzer','$2y$10$gqI8LIMg4PvsdU7Nl9P24.J9w8iqmqW7ZGY59uoviSHawG1p85T.u',0),
(104,'admin1','$2y$10$L4eYYLpwTsliGoZhCU5.g.qNnXdSURwV3Mm/dRA2.TLUWDVK8dqdi',1),
(105,'adminuss','$2y$10$Cw4RgAR4t64HQii4oT4lG.YhdFVHuhjIQ591DvTcPatsSeVbto0dm',1),
(106,'admin123','$2y$10$VB1zGWiM8dMDfUWhg3SnT.SD6boJl9AAorNlpYEHUXz.pJ5txdU8y',1),
(107,'bljus123','$2y$10$WrSSzFMSCPK2SkpChV9VCeVL1xaJJXzkcGyNv3LZrkImF8SQAzPeu',0);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
